# Generated by Django 4.0.3 on 2022-11-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WorkOrder', models.IntegerField()),
                ('PartNumber', models.CharField(max_length=200)),
                ('PartDescription', models.CharField(max_length=200)),
                ('ToolLocation', models.CharField(max_length=200)),
                ('Comment1', models.CharField(max_length=200)),
                ('Comment2', models.CharField(max_length=200)),
                ('Comment3', models.CharField(max_length=200)),
                ('PartTCs', models.CharField(max_length=200)),
                ('PartProbes', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RunDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName', models.CharField(max_length=200)),
                ('FilePath', models.CharField(max_length=200)),
                ('LoadNumber', models.IntegerField()),
                ('Equipment', models.CharField(max_length=200)),
                ('RunRecipe', models.CharField(max_length=200)),
                ('RunStart', models.DateTimeField()),
                ('RunEnd', models.DateTimeField()),
                ('RunDuration', models.FloatField()),
                ('FileLength', models.IntegerField()),
                ('OperatorName', models.CharField(max_length=200)),
                ('ExportControl', models.CharField(max_length=200)),
            ],
        ),
    ]
