# Generated by Django 4.0.3 on 2022-11-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rundetails',
            name='parts',
            field=models.ManyToManyField(to='main.partinformation'),
        ),
    ]
