# Generated by Django 4.0.3 on 2022-11-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_rundetails_loadnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partinformation',
            name='WorkOrder',
            field=models.CharField(max_length=200),
        ),
    ]
